# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"
silent: true
vars:
  # define APP name
  APP: apptest01
tasks:
  default:
    cmds: # 顺序执行
      - task: create-app
      - task: create-resource-base01
      - task: create-resource-base02
      - echo " All tasks completed!"

  create-resource-base01:
    desc: "Create and bind database resources"
    deps: # 并行执行
      - task: mysql-cluster
      - task: mongodb01
      - task: postgresql-cluster-17
      - task: minio
      - task: opensearch

  create-resource-base02:
    desc: "Create and bind database resources"
    deps: # 并行执行
      - task: grafana
      - task: flink

includes:
  create-app:
    taskfile: app/Taskfile.yml
    run: once
  mysql-cluster:
    taskfile: resource/Taskfile.yml
    # define variables for mysql-cluster
    vars:
      RESOURCE: "mysql-cluster"
      NAME: mysql01
      PLAN: standard-2c4g20
  mongodb01:
    taskfile: resource/Taskfile.yml
    # define variables for mongodb
    vars:
      RESOURCE: "mongodb"
      NAME: mongodb01
      PLAN: standard-2c4g20
  postgresql-cluster-17:
    taskfile: resource/Taskfile.yml
    # define variables for postgresql-cluster-17
    vars:
      RESOURCE: "postgresql-cluster-17"
      NAME: postgresql17-01
      PLAN: standard-2c4g20
      # 是否需要初始化数据库
      # 开启方式 设置为 true  否则不进行初始化
      # 开启后会执行 scripts/init-resources.sh 脚本, 根据业务逻辑进行脚本编写
      INIT: "true"
  grafana:
    taskfile: resource/Taskfile.yml
    vars:
      RESOURCE: "grafana"
      NAME: grafana01
      PLAN: standard-1c1g5
      # 是否依赖其他资源
      # 如果开启，则会将 DEPENDENT 变量传递给 prepare-resources.sh 脚本
      # 依赖的 PostgreSQL 数据库
      DEPENDENT: postgresql17-01
  minio:
    taskfile: resource/Taskfile.yml
    vars:
      RESOURCE: "minio"
      NAME: minio01
      PLAN: standard-v4s32
  flink:
    taskfile: resource/Taskfile.yml
    vars:
      RESOURCE: "flink"
      NAME: flink01
      PLAN: standard-2c4g5w
      # 依赖的 MinIO 存储服务
      DEPENDENT: minio01
  opensearch:
    taskfile: resource/Taskfile.yml
    vars:
      RESOURCE: "opensearch"
      NAME: opensearch01
      PLAN: standard-2c4g32
  fluentbit:
    taskfile: resource/Taskfile.yml
    vars:
      RESOURCE: "fluentbit"
      NAME: fluentbit01
      PLAN: standard-200m
      # 依赖的 OpenSearch 服务
      DEPENDENT: opensearch01
