# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  default:
    desc: Create APP
    cmds:
      - ./scripts/create-app.sh {{.APP}}
    silent: true
    ignore_error: true
